const lo = require('lodash');

const countryCodesAndNames = [
  {iso2: 'AF', iso3: 'AFG', label: 'Afghanistan', other: [], region: 'APAC'},
  {iso2: 'AX', iso3: 'ALA', label: 'Aland Islands', other: [], region: 'EMEA'},
  {iso2: 'AL', iso3: 'ALB', label: 'Albania', other: [], region: 'EMEA'},
  {iso2: 'AS', iso3: 'ASM', label: 'American Samoa', other: [], region: 'APAC'},
  {iso2: 'DZ', iso3: 'DZA', label: 'Algeria', other: [], region: 'EMEA'},
  {iso2: 'AD', iso3: 'AND', label: 'Andorra', other: [], region: 'EMEA'},
  {iso2: 'AO', iso3: 'AGO', label: 'Angola', other: [], region: 'EMEA'},
  {iso2: 'AI', iso3: 'AIA', label: 'Anguilla', other: [], region: 'LAD'},
  {iso2: 'AQ', iso3: 'ATA', label: 'Antarctica', other: []},
  {iso2: 'AG', iso3: 'ATG', label: 'Antigua and Barbuda', other: [], region: 'LAD'},
  {iso2: 'AR', iso3: 'ARG', label: 'Argentina', other: [], region: 'LAD'},
  {iso2: 'AM', iso3: 'ARM', label: 'Armenia', other: [], region: 'EMEA'},
  {iso2: 'AW', iso3: 'ABW', label: 'Aruba', other: [], region: 'LAD'},
  {iso2: 'AU', iso3: 'AUS', label: 'Australia', other: [], region: 'APAC'},
  {iso2: 'AT', iso3: 'AUT', label: 'Austria', other: ['Österreich'], region: 'EMEA'},
  {iso2: 'AZ', iso3: 'AZE', label: 'Azerbaijan', other: [], region: 'EMEA'},
  {iso2: 'BS', iso3: 'BHS', label: 'Bahamas', other: [], region: 'LAD'},
  {iso2: 'BH', iso3: 'BHR', label: 'Bahrain', other: [], region: 'EMEA'},
  {iso2: 'BD', iso3: 'BGD', label: 'Bangladesh', other: [], region: 'APAC'},
  {iso2: 'BB', iso3: 'BRB', label: 'Barbados', other: [], region: 'LAD'},
  {iso2: 'BY', iso3: 'BLR', label: 'Belarus', other: [], region: 'EMEA'},
  {iso2: 'BE', iso3: 'BEL', label: 'Belgium', other: [], region: 'EMEA'},
  {iso2: 'BZ', iso3: 'BLZ', label: 'Belize', other: [], region: 'LAD'},
  {iso2: 'BJ', iso3: 'BEN', label: 'Benin', other: [], region: 'EMEA'},
  {iso2: 'BM', iso3: 'BMU', label: 'Bermuda', other: [], region: 'LAD'},
  {iso2: 'BT', iso3: 'BTN', label: 'Bhutan', other: [], region: 'APAC'},
  {iso2: 'BO', iso3: 'BOL', label: 'Bolivia', other: ['Bolivia, Plurinational State of', 'Plurinational State of Bolivia'], region: 'LAD'},
  {iso2: 'BQ', iso3: 'BES', label: 'Bonaire, Sint Eustatius and Saba', other: []},
  {iso2: 'BA', iso3: 'BIH', label: 'Bosnia and Herzegovina', other: [], region: 'EMEA'},
  {iso2: 'BW', iso3: 'BWA', label: 'Botswana', other: [], region: 'EMEA'},
  {iso2: 'BV', iso3: 'BVT', label: 'Bouvet Island', other: []},
  {iso2: 'BR', iso3: 'BRA', label: 'Brazil', other: ['Brasil'], region: 'LAD'},
  {iso2: 'IO', iso3: 'IOT', label: 'British Indian Ocean Territory', other: [], region: 'APAC'},
  {iso2: 'BN', iso3: 'BRN', label: 'Brunei Darussalam', other: [], region: 'APAC'},
  {iso2: 'BG', iso3: 'BGR', label: 'Bulgaria', other: [], region: 'EMEA'},
  {iso2: 'BF', iso3: 'BFA', label: 'Burkina Faso', other: [], region: 'EMEA'},
  {iso2: 'BI', iso3: 'BDI', label: 'Burundi', other: [], region: 'EMEA'},
  {iso2: 'KH', iso3: 'KHM', label: 'Cambodia', other: [], region: 'APAC'},
  {iso2: 'CM', iso3: 'CMR', label: 'Cameroon', other: [], region: 'EMEA'},
  {iso2: 'CA', iso3: 'CAN', label: 'Canada', other: [], region: 'LAD'},
  {iso2: 'CV', iso3: 'CPV', label: 'Cape Verde', other: ['Cabo Verde'], region: 'EMEA'},
  {iso2: 'KY', iso3: 'CYM', label: 'Cayman Islands', other: [], region: 'LAD'},
  {iso2: 'CF', iso3: 'CAF', label: 'Central African Republic', other: ['CAR'], region: 'EMEA'},
  {iso2: 'TD', iso3: 'TCD', label: 'Chad', other: [], region: 'EMEA'},
  {iso2: 'CL', iso3: 'CHL', label: 'Chile', other: [], region: 'LAD'},
  {iso2: 'CN', iso3: 'CHN', label: 'China', other: [], region: 'APAC'},
  {iso2: 'CX', iso3: 'CXR', label: 'Christmas Island', other: [], region: 'APAC'},
  {iso2: 'CC', iso3: 'CCK', label: 'Cocos (Keeling) Islands', other: [], region: 'APAC'},
  {iso2: 'CO', iso3: 'COL', label: 'Colombia', other: [], region: 'LAD'},
  {iso2: 'KM', iso3: 'COM', label: 'Comoros', other: [], region: 'EMEA'},
  {iso2: 'CG', iso3: 'COG', label: 'Congo', other: ['Republic of Congo'], region: 'EMEA'},
  {iso2: 'CD', iso3: 'COD', label: 'Democratic Republic of the Congo', other: ['Congo, the Democratic Republic of the'], region: 'EMEA'},
  {iso2: 'CK', iso3: 'COK', label: 'Cook Islands', other: [], region: 'APAC'},
  {iso2: 'CR', iso3: 'CRI', label: 'Costa Rica', other: [], region: 'LAD'},
  {iso2: 'CI', iso3: 'CIV', label: "Côte d'Ivoire", other: ["Cote d'Ivoire", 'Ivory Coast', "Cote d'Ivoire (Ivory Coast)"], region: 'EMEA'},
  {iso2: 'HR', iso3: 'HRV', label: 'Croatia', other: [], region: 'EMEA'},
  {iso2: 'CU', iso3: 'CUB', label: 'Cuba', other: [], region: 'LAD'},
  {iso2: 'CW', iso3: 'CUW', label: 'Curaçao', other: [], region: 'LAD'},
  {iso2: 'CY', iso3: 'CYP', label: 'Cyprus', other: [], region: 'EMEA'},
  {iso2: 'CZ', iso3: 'CZE', label: 'Czech Republic', other: [], region: 'EMEA'},
  {iso2: 'DK', iso3: 'DNK', label: 'Denmark', other: ['Danmark'], region: 'EMEA'},
  {iso2: 'DJ', iso3: 'DJI', label: 'Djibouti', other: [], region: 'EMEA'},
  {iso2: 'DM', iso3: 'DMA', label: 'Dominica', other: [], region: 'LAD'},
  {iso2: 'DO', iso3: 'DOM', label: 'Dominican Republic', other: [], region: 'LAD'},
  {iso2: 'EC', iso3: 'ECU', label: 'Ecuador', other: [], region: 'LAD'},
  {iso2: 'EG', iso3: 'EGY', label: 'Egypt', other: [], region: 'EMEA'},
  {iso2: 'SV', iso3: 'SLV', label: 'El Salvador', other: [], region: 'LAD'},
  {iso2: 'GQ', iso3: 'GNQ', label: 'Equatorial Guinea', other: [], region: 'EMEA'},
  {iso2: 'ER', iso3: 'ERI', label: 'Eritrea', other: [], region: 'EMEA'},
  {iso2: 'EE', iso3: 'EST', label: 'Estonia', other: [], region: 'EMEA'},
  {iso2: 'ET', iso3: 'ETH', label: 'Ethiopia', other: [], region: 'EMEA'},
  {iso2: 'FK', iso3: 'FLK', label: 'Falkland Islands', other: ['Falkland Islands (Malvinas)', 'Malvinas'], region: 'LAD'},
  {iso2: 'FO', iso3: 'FRO', label: 'Faroe Islands', other: [], region: 'EMEA'},
  {iso2: 'FJ', iso3: 'FJI', label: 'Fiji', other: [], region: 'APAC'},
  {iso2: 'FI', iso3: 'FIN', label: 'Finland', other: [], region: 'EMEA'},
  {iso2: 'FR', iso3: 'FRA', label: 'France', other: [], region: 'EMEA'},
  {iso2: 'GF', iso3: 'GUF', label: 'French Guiana', other: [], region: 'LAD'},
  {iso2: 'PF', iso3: 'PYF', label: 'French Polynesia', other: [], region: 'APAC'},
  {iso2: 'TF', iso3: 'ATF', label: 'French Southern Territories', other: []},
  {iso2: 'FM', iso3: 'FSM', label: 'Micronesia', other: ['Micronesia (Federated States of)', 'Micronesia, Federated States of', 'Federated States of Micronesia'], region: 'APAC'},
  {iso2: 'GA', iso3: 'GAB', label: 'Gabon', other: [], region: 'EMEA'},
  {iso2: 'GM', iso3: 'GMB', label: 'Gambia', other: [], region: 'EMEA'},
  {iso2: 'GE', iso3: 'GEO', label: 'Georgia', other: [], region: 'EMEA'},
  {iso2: 'DE', iso3: 'DEU', label: 'Germany', other: ['Deutschland'], region: 'EMEA'},
  {iso2: 'GH', iso3: 'GHA', label: 'Ghana', other: [], region: 'EMEA'},
  {iso2: 'GI', iso3: 'GIB', label: 'Gibraltar', other: [], region: 'EMEA'},
  {iso2: 'GR', iso3: 'GRC', label: 'Greece', other: [], region: 'EMEA'},
  {iso2: 'GL', iso3: 'GRL', label: 'Greenland', other: [], region: 'EMEA'},
  {iso2: 'GD', iso3: 'GRD', label: 'Grenada', other: [], region: 'LAD'},
  {iso2: 'GP', iso3: 'GLP', label: 'Guadeloupe', other: [], region: 'LAD'},
  {iso2: 'GT', iso3: 'GTM', label: 'Guatemala', other: [], region: 'LAD'},
  {iso2: 'GG', iso3: 'GGY', label: 'Guernsey', other: [], region: 'EMEA'},
  {iso2: 'GN', iso3: 'GIN', label: 'Guinea', other: [], region: 'EMEA'},
  {iso2: 'GU', iso3: 'GUM', label: 'Guam', other: [], region: 'APAC'},
  {iso2: 'GW', iso3: 'GNB', label: 'Guinea-Bissau', other: [], region: 'EMEA'},
  {iso2: 'GY', iso3: 'GUY', label: 'Guyana', other: [], region: 'LAD'},
  {iso2: 'HT', iso3: 'HTI', label: 'Haiti', other: [], region: 'LAD'},
  {iso2: 'HM', iso3: 'HMD', label: 'Heard Island and McDonald Islands', other: []},
  {iso2: 'VA', iso3: 'VAT', label: 'Vatican City', other: ['Holy See (Vatican City State)'], region: 'EMEA'},
  {iso2: 'HK', iso3: 'HKG', label: 'Hong Kong', other: ['China (Hong Kong)'], region: 'APAC'},
  {iso2: 'HN', iso3: 'HND', label: 'Honduras', other: [], region: 'LAD'},
  {iso2: 'HU', iso3: 'HUN', label: 'Hungary', other: [], region: 'EMEA'},
  {iso2: 'IS', iso3: 'ISL', label: 'Iceland', other: [], region: 'EMEA'},
  {iso2: 'IN', iso3: 'IND', label: 'India', other: [], region: 'APAC'},
  {iso2: 'ID', iso3: 'IDN', label: 'Indonesia', other: [], region: 'APAC'},
  {iso2: 'IR', iso3: 'IRN', label: 'Iran', other: ['Iran, Islamic Republic of', 'Islamic Republic of Iran'], region: 'EMEA'},
  {iso2: 'IQ', iso3: 'IRQ', label: 'Iraq', other: [], region: 'EMEA'},
  {iso2: 'IE', iso3: 'IRL', label: 'Ireland', other: [], region: 'EMEA'},
  {iso2: 'IM', iso3: 'IMN', label: 'Isle of Man', other: [], region: 'EMEA'},
  {iso2: 'IL', iso3: 'ISR', label: 'Israel', other: [], region: 'EMEA'},
  {iso2: 'IT', iso3: 'ITA', label: 'Italy', other: ['Italia'], region: 'EMEA'},
  {iso2: 'JM', iso3: 'JAM', label: 'Jamaica', other: [], region: 'LAD'},
  {iso2: 'JP', iso3: 'JPN', label: 'Japan', other: [], region: 'EMEA'},
  {iso2: 'JE', iso3: 'JEY', label: 'Jersey', other: [], region: 'EMEA'},
  {iso2: 'JO', iso3: 'JOR', label: 'Jordan', other: [], region: 'EMEA'},
  {iso2: 'KZ', iso3: 'KAZ', label: 'Kazakhstan', other: [], region: 'EMEA'},
  {iso2: 'KE', iso3: 'KEN', label: 'Kenya', other: [], region: 'EMEA'},
  {iso2: 'KI', iso3: 'KIR', label: 'Kiribati', other: [], region: 'APAC'},
  {iso2: 'KP', iso3: 'PRK', label: 'North Korea', other: ["Korea, Democratic People's Republic of", 'DPRK', "Democratic People's Republic of Korea"], region: 'APAC'},
  {iso2: 'KR', iso3: 'KOR', label: 'South Korea', other: ['Korea, Republic of', 'Republic of Korea', 'Korea', 'Korea (South)'], region: 'APAC'},
  {iso2: 'KW', iso3: 'KWT', label: 'Kuwait', other: [], region: 'EMEA'},
  {iso2: 'KG', iso3: 'KGZ', label: 'Kyrgyzstan', other: [], region: 'EMEA'},
  {iso2: 'LA', iso3: 'LAO', label: 'Laos', other: ["Lao People's Democratic Republic", 'Lao Peoples Democratic Republic'], region: 'APAC'},
  {iso2: 'LV', iso3: 'LVA', label: 'Latvia', other: [], region: 'EMEA'},
  {iso2: 'LB', iso3: 'LBN', label: 'Lebanon', other: [], region: 'EMEA'},
  {iso2: 'LS', iso3: 'LSO', label: 'Lesotho', other: [], region: 'EMEA'},
  {iso2: 'LR', iso3: 'LBR', label: 'Liberia', other: [], region: 'EMEA'},
  {iso2: 'LY', iso3: 'LBY', label: 'Libya', other: [], region: 'EMEA'},
  {iso2: 'LI', iso3: 'LIE', label: 'Liechtenstein', other: [], region: 'EMEA'},
  {iso2: 'LT', iso3: 'LTU', label: 'Lithuania', other: [], region: 'EMEA'},
  {iso2: 'LU', iso3: 'LUX', label: 'Luxembourg', other: ['Luxemburg'], region: 'EMEA'},
  {iso2: 'MO', iso3: 'MAC', label: 'Macao', other: [], region: 'APAC'},
  {iso2: 'MK', iso3: 'MKD', label: 'Macedonia', other: []},
  {iso2: 'MG', iso3: 'MDG', label: 'Madagascar', other: [], region: 'EMEA'},
  {iso2: 'MH', iso3: 'MHL', label: 'Marshall Islands', other: [], region: 'APAC'},
  {iso2: 'MW', iso3: 'MWI', label: 'Malawi', other: [], region: 'EMEA'},
  {iso2: 'MY', iso3: 'MYS', label: 'Malaysia', other: [], region: 'APAC'},
  {iso2: 'MV', iso3: 'MDV', label: 'Maldives', other: [], region: 'APAC'},
  {iso2: 'ML', iso3: 'MLI', label: 'Mali', other: [], region: 'EMEA'},
  {iso2: 'MT', iso3: 'MLT', label: 'Malta', other: [], region: 'EMEA'},
  {iso2: 'MQ', iso3: 'MTQ', label: 'Martinique', other: [], region: 'LAD'},
  {iso2: 'MR', iso3: 'MRT', label: 'Mauritania', other: [], region: 'EMEA'},
  {iso2: 'MU', iso3: 'MUS', label: 'Mauritius', other: [], region: 'EMEA'},
  {iso2: 'YT', iso3: 'MYT', label: 'Mayotte', other: ['Mayote'], region: 'EMEA'},
  {iso2: 'MX', iso3: 'MEX', label: 'Mexico', other: [], region: 'LAD'},
  {iso2: 'MD', iso3: 'MDA', label: 'Moldova', other: ['Republic of Moldova', 'Moldova, Republic of'], region: 'EMEA'},
  {iso2: 'MC', iso3: 'MCO', label: 'Monaco', other: [], region: 'EMEA'},
  {iso2: 'MN', iso3: 'MNG', label: 'Mongolia', other: [], region: 'EMEA'},
  {iso2: 'ME', iso3: 'MNE', label: 'Montenegro', other: [], region: 'EMEA'},
  {iso2: 'MS', iso3: 'MSR', label: 'Montserrat', other: [], region: 'LAD'},
  {iso2: 'MA', iso3: 'MAR', label: 'Morocco', other: [], region: 'EMEA'},
  {iso2: 'MZ', iso3: 'MOZ', label: 'Mozambique', other: [], region: 'EMEA'},
  {iso2: 'MM', iso3: 'MMR', label: 'Myanmar', other: ['Burma'], region: 'APAC'},
  {iso2: 'NA', iso3: 'NAM', label: 'Namibia', other: []},
  {iso2: 'NR', iso3: 'NRU', label: 'Nauru', other: [], region: 'APAC'},
  {iso2: 'NP', iso3: 'NPL', label: 'Nepal', other: [], region: 'APAC'},
  {iso2: 'NL', iso3: 'NLD', label: 'Netherlands', other: ['The Netherlands', 'Nederland'], region: 'EMEA'},
  // {iso2: "AN", iso3: "", label: "Netherlands Antilles", other: ['Antilles (Netherlands)']}
  {iso2: 'NC', iso3: 'NCL', label: 'New Caledonia', other: [], region: 'APAC'},
  {iso2: 'NZ', iso3: 'NZL', label: 'New Zealand', other: [], region: 'APAC'},
  {iso2: 'NI', iso3: 'NIC', label: 'Nicaragua', other: [], region: 'LAD'},
  {iso2: 'NE', iso3: 'NER', label: 'Niger', other: [], region: 'EMEA'},
  {iso2: 'NG', iso3: 'NGA', label: 'Nigeria', other: [], region: 'EMEA'},
  {iso2: 'NU', iso3: 'NIU', label: 'Niue', other: []},
  {iso2: 'NF', iso3: 'NFK', label: 'Norfolk Island', other: []},
  {iso2: 'MP', iso3: 'MNP', label: 'Northern Mariana Islands', other: [], region: 'APAC'},
  {iso2: 'NO', iso3: 'NOR', label: 'Norway', other: ['Norge'], region: 'EMEA'},
  {iso2: 'OM', iso3: 'OMN', label: 'Oman', other: [], region: 'EMEA'},
  {iso2: 'PK', iso3: 'PAK', label: 'Pakistan', other: [], region: 'APAC'},
  {iso2: 'PS', iso3: 'PSE', label: 'Palestine', other: ['Palestinian Territory', 'Palestine, State of'], region: 'EMEA'},
  {iso2: 'PA', iso3: 'PAN', label: 'Panama', other: [], region: 'LAD'},
  {iso2: 'PG', iso3: 'PNG', label: 'Papua New Guinea', other: [], region: 'APAC'},
  {iso2: 'PY', iso3: 'PRY', label: 'Paraguay', other: [], region: 'LAD'},
  {iso2: 'PE', iso3: 'PER', label: 'Peru', other: [], region: 'LAD'},
  {iso2: 'PH', iso3: 'PHL', label: 'Philippines', other: [], region: 'APAC'},
  {iso2: 'PN', iso3: 'PCN', label: 'Pitcairn', other: []},
  {iso2: 'PL', iso3: 'POL', label: 'Poland', other: ['Polska'], region: 'EMEA'},
  {iso2: 'PT', iso3: 'PRT', label: 'Portugal', other: [], region: 'EMEA'},
  {iso2: 'PR', iso3: 'PRI', label: 'Puerto Rico', other: [], region: 'LAD'},
  {iso2: 'PW', iso3: 'PLW', label: 'Palau', other: [], region: 'APAC'},
  {iso2: 'QA', iso3: 'QAT', label: 'Qatar', other: [], region: 'EMEA'},
  {iso2: 'RE', iso3: 'REU', label: 'Reunion', other: [], region: 'EMEA'},
  {iso2: 'RO', iso3: 'ROU', label: 'Romania', other: ['ROM'], region: 'EMEA'},
  {iso2: 'RU', iso3: 'RUS', label: 'Russia', other: ['Russian Federation'], region: 'EMEA'},
  {iso2: 'RW', iso3: 'RWA', label: 'Rwanda', other: [], region: 'EMEA'},
  {iso2: 'BL', iso3: 'BLM', label: 'Saint Barthélemy', other: ['Saint Barthelemy'], region: 'EMEA'},
  {iso2: 'SH', iso3: 'SHN', label: 'Saint Helena, Ascension and Tristan da Cunha', other: ['Ascension Island'], region: 'EMEA'},
  {iso2: 'KN', iso3: 'KNA', label: 'Saint Kitts and Nevis', other: [], region: 'LAD'},
  {iso2: 'LC', iso3: 'LCA', label: 'Saint Lucia', other: [], region: 'LAD'},
  {iso2: 'MF', iso3: 'MAF', label: 'Saint Martin', other: ['Saint Martin (French part)', 'Saint Martin (France)', 'Saint-Martin (France)'], region: 'EMEA'},
  {iso2: 'PM', iso3: 'SPM', label: 'Saint Pierre and Miquelon', other: [], region: 'EMEA'},
  {iso2: 'VC', iso3: 'VCT', label: 'Saint Vincent and the Grenadines', other: [], region: 'LAD'},
  {iso2: 'WS', iso3: 'WSM', label: 'Samoa', other: [], region: 'APAC'},
  {iso2: 'SM', iso3: 'SMR', label: 'San Marino', other: [], region: 'EMEA'},
  {iso2: 'ST', iso3: 'STP', label: 'Sao Tome and Principe', other: [], region: 'EMEA'},
  {iso2: 'SA', iso3: 'SAU', label: 'Saudi Arabia', other: [], region: 'EMEA'},
  {iso2: 'SN', iso3: 'SEN', label: 'Senegal', other: [], region: 'EMEA'},
  {iso2: 'RS', iso3: 'SRB', label: 'Serbia', other: ['CSS'], region: 'EMEA'},
  {iso2: 'SC', iso3: 'SYC', label: 'Seychelles', other: [], region: 'EMEA'},
  {iso2: 'SL', iso3: 'SLE', label: 'Sierra Leone', other: [], region: 'EMEA'},
  {iso2: 'SG', iso3: 'SGP', label: 'Singapore', other: [], region: 'APAC'},
  {iso2: 'SX', iso3: 'SXM', label: 'Sint Maarten (Dutch part)', other: ['Sint Maarten']},
  {iso2: 'SK', iso3: 'SVK', label: 'Slovakia', other: ['Slovak Republic', 'Slovakia (Slovak Republic)'], region: 'EMEA'},
  {iso2: 'SI', iso3: 'SVN', label: 'Slovenia', other: [], region: 'EMEA'},
  {iso2: 'SB', iso3: 'SLB', label: 'Solomon Islands', other: [], region: 'APAC'},
  {iso2: 'SO', iso3: 'SOM', label: 'Somalia', other: [], region: 'EMEA'},
  {iso2: 'ZA', iso3: 'ZAF', label: 'South Africa', other: [], region: 'EMEA'},
  {iso2: 'GS', iso3: 'SGS', label: 'South Georgia and the South Sandwich Islands', other: []},
  {iso2: 'SS', iso3: 'SSD', label: 'South Sudan', other: [], region: 'EMEA'},
  {iso2: 'ES', iso3: 'ESP', label: 'Spain', other: ['España'], region: 'EMEA'},
  {iso2: 'LK', iso3: 'LKA', label: 'Sri Lanka', other: [], region: 'APAC'},
  {iso2: 'SD', iso3: 'SDN', label: 'Sudan', other: [], region: 'EMEA'},
  {iso2: 'SR', iso3: 'SUR', label: 'Suriname', other: [], region: 'LAD'},
  {iso2: 'SJ', iso3: 'SJM', label: 'Svalbard and Jan Mayen', other: [], region: 'EMEA'},
  {iso2: 'SZ', iso3: 'SWZ', label: 'Swaziland', other: []},
  {iso2: 'SE', iso3: 'SWE', label: 'Sweden', other: ['Sverige'], region: 'EMEA'},
  {iso2: 'CH', iso3: 'CHE', label: 'Switzerland', other: ['Suisse', 'Schweiz'], region: 'EMEA'},
  {iso2: 'SY', iso3: 'SYR', label: 'Syria', other: ['Syrian Arab Republic'], region: 'EMEA'},
  {iso2: 'TW', iso3: 'TWN', label: 'Taiwan', other: [], region: 'APAC'},
  {iso2: 'TJ', iso3: 'TJK', label: 'Tajikistan', other: [], region: 'EMEA'},
  {iso2: 'TZ', iso3: 'TZA', label: 'Tanzania', other: ['Tanzania, United Republic of', 'United Republic of Tanzania', 'TAN'], region: 'EMEA'},
  {iso2: 'TH', iso3: 'THA', label: 'Thailand', other: [], region: 'APAC'},
  {iso2: 'TL', iso3: 'TLS', label: 'Timor-Leste', other: ['East Timor', 'Portuguese Timor'], region: 'APAC'},
  {iso2: 'TG', iso3: 'TGO', label: 'Togo', other: [], region: 'EMEA'},
  {iso2: 'TK', iso3: 'TKL', label: 'Tokelau', other: [], region: 'APAC'},
  {iso2: 'TO', iso3: 'TON', label: 'Tonga', other: [], region: 'APAC'},
  {iso2: 'TT', iso3: 'TTO', label: 'Trinidad and Tobago', other: [], region: 'LAD'},
  {iso2: 'TN', iso3: 'TUN', label: 'Tunisia', other: [], region: 'EMEA'},
  {iso2: 'TR', iso3: 'TUR', label: 'Turkey', other: ['Türkiye'], region: 'EMEA'},
  {iso2: 'TM', iso3: 'TKM', label: 'Turkmenistan', other: [], region: 'EMEA'},
  {iso2: 'TC', iso3: 'TCA', label: 'Turks and Caicos Islands', other: ['Turks and Caicos'], region: 'LAD'},
  {iso2: 'TV', iso3: 'TUV', label: 'Tuvalu', other: [], region: 'APAC'},
  {iso2: 'UG', iso3: 'UGA', label: 'Uganda', other: [], region: 'EMEA'},
  {iso2: 'UA', iso3: 'UKR', label: 'Ukraine', other: [], region: 'EMEA'},
  {iso2: 'AE', iso3: 'ARE', label: 'United Arab Emirates', other: ['UAE', 'U.A.E.'], region: 'EMEA'},
  {iso2: 'GB', iso3: 'GBR', label: 'United Kingdom', other: ['Great Britain', 'UK', 'Britain', 'England'], region: 'EMEA'},
  {iso2: 'US', iso3: 'USA', label: 'United States', other: ['United States of America', 'U.S.A.', 'America'], region: 'LAD'},
  {iso2: 'UM', iso3: 'UMI', label: 'United States Minor Outlying Islands', other: [], region: 'LAD'},
  {iso2: 'UY', iso3: 'URY', label: 'Uruguay', other: [], region: 'LAD'},
  {iso2: 'UZ', iso3: 'UZB', label: 'Uzbekistan', other: [], region: 'EMEA'},
  {iso2: 'VU', iso3: 'VUT', label: 'Vanuatu', other: [], region: 'APAC'},
  {iso2: 'VE', iso3: 'VEN', label: 'Venezuela', other: ['Venezuela, Bolivarian Republic of', 'Bolivarian Republic of Venezuela'], region: 'LAD'},
  {iso2: 'VI', iso3: 'VIR', label: 'Virgin Islands', other: ['US Virgin Islands', 'U.S. Virgin Islands'], region: 'LAD'},
  {iso2: 'VN', iso3: 'VNM', label: 'Vietnam', other: ['Viet Nam', 'Việt Nam'], region: 'APAC'},
  {iso2: 'VG', iso3: 'VGB', label: 'British Virgin Islands', other: ['Virgin Islands, British'], region: 'LAD'},
  {iso2: 'WF', iso3: 'WLF', label: 'Wallis and Futuna', other: [], region: 'APAC'},
  {iso2: 'EH', iso3: 'ESH', label: 'Western Sahara', other: [], region: 'EMEA'},
  {iso2: 'YE', iso3: 'YEM', label: 'Yemen', other: [], region: 'EMEA'},
  {iso2: 'ZM', iso3: 'ZMB', label: 'Zambia', other: [], region: 'EMEA'},
  {iso2: 'ZW', iso3: 'ZWE', label: 'Zimbabwe', other: [], region: 'EMEA'}
];

  // const label = lo.map(lo.map(countryCodesAndNames, 'label'), lo.toUpper);
  const region = 'APAC';
  const label = lo.map(countryCodesAndNames, 'label');
  const filter = lo.filter(countryCodesAndNames, {'region': region});
  const iso2 = lo.map(lo.filter(countryCodesAndNames,{'region': region}), 'iso2');
  const iso3 = lo.map(countryCodesAndNames, 'iso3');

  // console.log(iso2.join(','));
  console.log(filter);
  
  
  // console.log(lo.union(label, iso2, iso3).join('|'));

  // console.log(lo.map(countryCodesAndNames,'label').join('|'));
  var companyName = "MX Services Sign and Lighting Maintenance";

  
  var newRegex = new RegExp("\\b(?:" + lo.union(label, iso2, iso3).join('|') + ")\\b", "gi");
  let result = companyName.match(newRegex) || []; 
  // console.log(result);

  // const {iso2, iso3} = countryCodesAndNames.find(element => element.label.localeCompare("Argentina") == 0);
  // console.log(iso2, iso3);
  

//   console.log(companyName.match(regex));


// let newArray = [];
// for (country of countryCodesAndNames) {
//     var tempObject = {};
//     tempObject.iso2 = country.iso2;
//     tempObject.iso3 = country.iso3;
//     tempObject.label = country.label;
//     newArray.push(tempObject);
//     if (country.other.length > 0) {
//         country.other.forEach((el) => {
//             let newObject = {...tempObject};
//             newObject.label = el;
//             newArray.push(newObject);
//         });
//     }
    
// }
// console.log("THEN THE ARRAY");
// console.log(newArray);
// newArray.forEach((el, i) => console.log(el, i));